name: seo_service
description: A new Flutter package.
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.2

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.3.3
  rxdart: ^0.27.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

